name: hw1_env
dependencies: 
  - python=3.8
  - pip
  - pip: 
    - matplotlib==3.3.4
    - numpy==1.20.1
    - pandas==1.2.4
    - scikit-learn==0.24.1
    - seaborn==0.11.1
    - xgboost==1.3.3
    - lightgbm==3.2.1
